<section id="historiaPHP">

    <div class="container">
        <div class="titulo">
            <h1>História da Fundação da Nossa Cidade</h1>
        </div>
        </br>

        <p style="text-align: justify;">O Guar&aacute; foi constru&iacute;do em 1967. As primeiras oitocentas resid&ecirc;ncias foram constru&iacute;das atrav&eacute;s do sistema de&nbsp;mutir&atilde;o&nbsp;pelos funcion&aacute;rios da&nbsp;Novacap, que nelas iriam morar em&nbsp;21 de abril&nbsp;de&nbsp;1969.</p>
        <img src="img/hitoriaGuara1.jpg" class="img-responsive center-block" alt="Responsive image" style="width: 50%">
        <p style="text-align: justify;">Em setembro de&nbsp;1969, a Novacap e a Secretaria de Habita&ccedil;&atilde;o e Interesse Social - SHIS (hoje, extinta) prosseguiram com a urbaniza&ccedil;&atilde;o do segundo trecho, o Guar&aacute; II (bairro do Guar&aacute;), inaugurado em 2 de mar&ccedil;o de 1972, para abrigar funcion&aacute;rios do Governo Federal. O Decreto 2 356, de 31 de agosto de 1973, criou a Administra&ccedil;&atilde;o Regional do Setor Residencial Ind&uacute;stria e Abastecimento, composta pelo Guar&aacute; I (bairro do Guar&aacute;), Guar&aacute; II e o Setor Residencial Ind&uacute;stria e Abastecimento (setor do Guar&aacute;).</p>
        <img src="img/hitoriaGuara2.jpg" class="img-responsive center-block" alt="Responsive image" style="width: 50%">
        <p style="text-align: justify;">Com o advento do Decreto 11921, em 25 de outubro de 1989, o Guar&aacute;, at&eacute; ent&atilde;o denominado Setor Residencial Ind&uacute;stria e Abastecimento e ocupando uma &aacute;rea de 8,6&nbsp;km&sup2;, passou a ter uma &aacute;rea de 45,66&nbsp;km&sup2;, sendo, ent&atilde;o, criada a regi&atilde;o administrativa do Guar&aacute;.</p>
        <img src="img/hitoriaGuara3.jpg" class="img-responsive center-block" alt="Responsive image" style="width: 50%">
        <p style="text-align: justify;">Anteriormente pertencentes &agrave; regi&atilde;o administrativa do Guar&aacute;, o&nbsp;Setor de Ind&uacute;stria e Abastecimento, o Setor de Inflam&aacute;veis e o Setor de Transporte Rodovi&aacute;rio de Cargas passaram, em julho de 2005, a formar outra regi&atilde;o administrativa distinta. A&nbsp;Cidade Estrutural&nbsp;tamb&eacute;m j&aacute; pertenceu &agrave; regi&atilde;o administrativa do Guar&aacute;, por&eacute;m, desde 2004, pertence ao Setor de Ind&uacute;stria e Abastecimento, nomeada&nbsp;Setor Complementar de Ind&uacute;stria e Abastecimento.</p>
        <p style="text-align: justify;">O&nbsp;padroeiro&nbsp;da cidade &eacute;&nbsp;S&atilde;o Paulo Ap&oacute;stolo, cuja&nbsp;festa lit&uacute;rgica&nbsp;se d&aacute; em&nbsp;04 de julho, sendo, essa data, dia de&nbsp;ponto facultativo&nbsp;na cidade, conforme a Lei 2908 de 5 de fevereiro de 2002.</p>
        <p style="text-align: justify;">O nome da regi&atilde;o administrativa tem, como origem, o&nbsp;C&oacute;rrego Guar&aacute;, que corta toda sua &aacute;rea, sendo batizado em homenagem ao&nbsp;lobo-guar&aacute;, esp&eacute;cie comum no&nbsp;Planalto Central. A palavra Guar&aacute; deriva do<em>tupi auar&aacute;</em>, significa "Vermelho" e &eacute; associada tanto ao&nbsp;lobo-Guar&aacute;&nbsp;quanto a Ave-Guar&aacute;.&nbsp;</p>
        <img src="img/hitoriaGuara4.jpg" class="img-responsive center-block" alt="Responsive image" style="width: 50%">
        <p style="text-align: justify;">A regi&atilde;o administrativa do Guar&aacute; est&aacute; assentada sobre uma&nbsp;topografia&nbsp;plana, de embasamento de&nbsp;ard&oacute;sia&nbsp;e&nbsp;quartzito, da s&eacute;rie do Bambu do Cambio Ordoviciano.</p>
        <p style="text-align: justify;">Circundado em faixas vari&aacute;veis, tal que, do&nbsp;c&oacute;rrego&nbsp;do Guar&aacute; com aluvi&atilde;o do quatern&aacute;rio (Qa) constitu&iacute;do de&nbsp;areia&nbsp;e&nbsp;argila&nbsp;n&atilde;o consolidada, podendo acrescentar em algumas &aacute;reas a argila turfosa at&eacute; a&nbsp;turfa, na lista de seus membros litol&oacute;gicos, em altitudes vari&aacute;veis entre 1055 metros. Possui solos muito pl&aacute;sticos e satur&aacute;veis, facilmente cobertos por&nbsp;cerrado, cerrad&atilde;o,&nbsp;mata ciliar&nbsp;e&nbsp;reflorestamento.</p>
        <p style="text-align: justify;">No Guar&aacute;, a rede de drenagem &eacute; composta de cursos d&rsquo;&aacute;gua que fazem parte da&nbsp;Bacia do Parano&aacute;, cabendo destaque para os c&oacute;rregos&nbsp;Vicente Pires, a oeste, e&nbsp;Guar&aacute;, a leste.</p>
        <p style="text-align: justify;">Segundo a&nbsp;classifica&ccedil;&atilde;o de K&ouml;ppen, internacionalmente adotada, os tipos de clima do&nbsp;Distrito Federal, assim como de toda a&nbsp;Regi&atilde;o Centro-Oeste do Brasil, apresentam dois subdom&iacute;nios ou variedades: clima quente e semi&uacute;mido. Observa-se, assim, a exist&ecirc;ncia de duas esta&ccedil;&otilde;es: uma, chuvosa, no ver&atilde;o (outubro a abril) e outra, seca, no inverno (maio a setembro). A temperatura m&eacute;dia &eacute; de 21 graus cent&iacute;grados.</p>
        <p style="text-align: justify;">A regi&atilde;o administrativa do Guar&aacute; atualmente compreende a &aacute;rea urbana composta pelo Guar&aacute; I e II, as Quadras Econ&ocirc;micas L&uacute;cio Costa, Setor de Oficinas Sul, Setor de Clubes e Est&aacute;dios Esportivos Sul e Setor de &Aacute;reas Isoladas Sudoeste. A cidade &eacute; formada por quadras residenciais, com casas e blocos de apartamentos, al&eacute;m de &aacute;reas espec&iacute;ficas para com&eacute;rcio, oficinas e pequenas ind&uacute;strias.</p>
        <p style="text-align: justify;">O Guar&aacute; I &eacute; formado por seis quadras com numera&ccedil;&atilde;o &iacute;mpar (1 a 11) e onze quadras com numera&ccedil;&atilde;o par (2 a 22). Cada quadra engloba um determinado n&uacute;mero de blocos de apartamentos, pr&eacute;dios comerciais e conjuntos de casas, identificados por letras do alfabeto (bloco A, conjunto B, etc.). A disposi&ccedil;&atilde;o das quadras no Guar&aacute; I segue um padr&atilde;o, formando uma s&eacute;rie de quadril&aacute;teros. Os blocos e casas situados dentro de cada quadril&aacute;tero formam uma Quadra Interna. J&aacute; os blocos e casas situados ao redor do quadril&aacute;tero formam a Quadra Externa. Assim, forma-se o endere&ccedil;amento das quadras na cidade: Quadra Externa 1, Quadra Interna 1, Quadra Externa 2, Quadra Interna 2 e assim por diante.</p>
        <p style="text-align: justify;">O Guar&aacute; II &eacute; formado majoritariamente por grandes quadras residenciais em formato quadrangular, compostas por um n&uacute;mero vari&aacute;vel de conjuntos de casas. Cada conjunto &eacute; identificado por uma letra do alfabeto (A, B, C, etc.) e essas quadras residenciais s&atilde;o chamadas de Quadras Externas. Elas recebem numera&ccedil;&atilde;o de 13 a 21 (&iacute;mpares) e de 24 a 48 (pares). J&aacute; as Quadras Internas, no Guar&aacute; II, correspondem ao "miolo" central da cidade, composto por pr&eacute;dios de apartamentos. As quadras internas do Guar&aacute; II recebem somente numera&ccedil;&atilde;o &iacute;mpar (23 a 33), e os lotes onde se situam os pr&eacute;dios s&atilde;o identificados por n&uacute;meros (lote 1, lote 2, etc.)</p>
        <p style="text-align: justify;">Tamb&eacute;m no Guar&aacute; II situa-se o Centro Administrativo, Vivencial e Esportivo (CAVE), onde encontram-se a Administra&ccedil;&atilde;o Regional da cidade e a&nbsp;Feira do Guar&aacute;, al&eacute;m de um complexo esportivo com est&aacute;dio de futebol, gin&aacute;sio de esportes,&nbsp;cart&oacute;dromo&nbsp;e quadras poliesportivas.</p>
        <p style="text-align: justify;">A cidade conta com dois terminais de &ocirc;nibus urbanos: um na Quadra Externa 16, no Guar&aacute; I, e outro na Avenida Contorno do Guar&aacute; II. Possui, ainda, duas esta&ccedil;&otilde;es do&nbsp;Metr&ocirc; de Bras&iacute;lia: a esta&ccedil;&atilde;o Feira, em opera&ccedil;&atilde;o desde2001, e a esta&ccedil;&atilde;o Guar&aacute;, inaugurada em&nbsp;2010. Os escassos investimentos em transporte p&uacute;blico ao longo das &uacute;ltimas tr&ecirc;s d&eacute;cadas fizeram com que cada vez mais moradores do Guar&aacute; optassem pelo uso do autom&oacute;vel particular em seus deslocamentos para outras regi&otilde;es administrativas do Distrito Federal. A consequ&ecirc;ncia natural desse quadro foi o aumento da ocorr&ecirc;ncia de engarrafamentos nos acessos e sa&iacute;das da cidade, que se tornaram um dos grandes problemas enfrentados atualmente pela comunidade do Guar&aacute;.</p>
        <p style="text-align: justify;">Altera&ccedil;&otilde;es recentes no Plano Diretor da cidade permitiram a constru&ccedil;&atilde;o de pr&eacute;dios mais altos e fora do miolo do Guar&aacute; II, al&eacute;m da cria&ccedil;&atilde;o de novas quadras residenciais em &aacute;reas lim&iacute;trofes com&nbsp;Candangol&acirc;ndia&nbsp;e&nbsp;N&uacute;cleo Bandeirante. A expans&atilde;o da &aacute;rea urbana do Guar&aacute; dever&aacute; causar um aumento consider&aacute;vel na popula&ccedil;&atilde;o da cidade, com impacto na infraestrutura atualmente oferecida. A expectativa oficial &eacute; de que, at&eacute; 2012, a popula&ccedil;&atilde;o cres&ccedil;a at&eacute; 20 por cento.<sup>[4]</sup>&nbsp;O Guar&aacute; mudou totalmente o seu perfil nos &uacute;ltimos quarenta anos, concentrando, hoje, grande parte da&nbsp;classe m&eacute;dia&nbsp;do Distrito Federal. As casas originais da &eacute;poca do&nbsp;mutir&atilde;o, constru&iacute;das pela antiga Sociedade Habitacional de Interesse Social nas d&eacute;cadas de 1960 e 1970, cederam lugar para sobrados e condom&iacute;nios de bom n&iacute;vel, evidenciando a sele&ccedil;&atilde;o socioecon&ocirc;mica de sua popula&ccedil;&atilde;o. Segundo pesquisas da Codeplan, o Guar&aacute; tem a sexta maior renda&nbsp;<em>per capita</em>&nbsp;entre as regi&otilde;es administrativas do Distrito Federal.</p>
        <p style="text-align: justify;">A &aacute;rea dos terrenos das casas chega a, no m&aacute;ximo, 360 metros quadrados. Devido ao tamanho limitado dos terrenos, combinado com a valoriza&ccedil;&atilde;o imobili&aacute;ria da regi&atilde;o, o Guar&aacute; tem um dos metros quadrados de im&oacute;veis mais caros do Distrito Federal. A arquitetura das casas prima pela criatividade, com uma grande variedade de projetos interessantes e diferentes de casas t&eacute;rreas e sobrados. O Guar&aacute; surgiu como um loteamento destinado a moradia popular. A partir de meados da d&eacute;cada de 1980, o perfil socioecon&ocirc;mico da cidade mudou. Hoje, o Guar&aacute; &eacute; considerado um dos principais redutos de classe m&eacute;dia do Distrito Federal. A Quadra Externa 15, no Guar&aacute; II, &eacute; a maior quadra da cidade em n&uacute;mero de ruas de casas, com 23 conjuntos. A Quadra Externa 01, no Guar&aacute; I &eacute; a menor, com seis conjuntos. As quadras internas do Guar&aacute; I t&ecirc;m tra&ccedil;ado&nbsp;sim&eacute;trico. Assim, a disposi&ccedil;&atilde;o dos blocos e conjuntos de casa dentro de uma determinada quadra interna repete-se nas demais. Por exemplo: o conjunto D est&aacute; sempre no meio da quadra; o bloco P est&aacute; sempre ao lado do conjunto R, etc. No Guar&aacute;, existe uma&nbsp;escola de samba&nbsp;chamada&nbsp;Imp&eacute;rio do Guar&aacute;, fundada no ano de 1988.</p>



    </div>



</section>
